name: ${pluginName}
version: ${pluginVersion}
api-version: "${bukkitApiVersion}"
author: ${authors}
description: ${description}

main: ${bukkitPluginMain}
website: ${website}

softdepend: [ProtocolLib]

load: STARTUP
