name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  MVN_REPO_SERVER_ID: "startail-public"

jobs:
  maven:
    name: deploy-maven
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Build and Deploy
        run: |
          cat <<EOT > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>${{ env.MVN_REPO_SERVER_ID }}</id>
                <username>${{ secrets.MVN_REPO_USERNAME }}</username>
                <password>${{ secrets.MVN_REPO_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOT
          mvn clean package deploy
